### ISSUE TITLE
"Odin.uplugin" should not have "CanContainContent: true"

### ISSUE THREAD

**Issue by healermagnus** [4Players/odin-sdk-unreal#1]
This is a very minor thing, but "Odin.uplugin" should not have "CanContainContent: true"

it should be 

"CanContainContent": false

Because there is no content, and I'm trying to reduce the number of "empty" entries in my multi-plugin project in the Content Browser.

I can change it for my project, but that would mean I need to commit your plugin to my repository for other developers and cloud building.  We link directly to your plugin, unmodified, and I would like to keep it that way. :)

**Comment by svenpaulsen** [comment]
Thanks for the feedback! I've updated the `.uplugin` file and this will be part of our next release. :smile:
